// export const endpoints = {
//   baseUrl: "http://localhost:4000",
//   employees: "/users",
//   menu: "/menu",
//   points: "/points",
//   branches: "/branches",
//   roles: "/roles",
//   branchList: "/branchList",
//   roleList: "/roleList",
//   pointsEarnedByDriver: "/pointsEarnedByDriver",
//   pointReqHistory: "/pointReqHistory",
//   pointsRequested: "/pointsRequested",
//   createEmp: "/createEmp",
//   createBranch: "/createBranch",
//   createRole: "/createRole",
//   givePoint: "/givePoint",
//   userOptions: "/userOptions",
//   login: "/login",
//   logout: "/logout",
// };

export const endpoints = {
  baseUrl: "https://krt-backend-json-server-production-5cc1.up.railway.app",
  employees: "/user/getAllUsers",
  menu: "/getUiMenu",
  points: "/webRequest/driverInfo",
  branches: "/branchList",
  roles: "/roleList",
  branchList: "/branchList",
  roleList: "/roleList",
  pointsEarnedByDriver: "/pointsEarnedByDriver",
  pointReqHistory: "/pointReqHistory",
  pointsRequested: "/points/withdrawRequest",
  createEmp: "/createEmp",
  createBranch: "/createBranch",
  createRole: "/createRole",
  givePoint: "/givePoint",
  userOptions: "/userOptions",
  creditPoint: "/creditPoint",
  pointRequestFromBM: "/pointRequestFromBM",
  login: "/auth/login",
  logout: "/logout",
};
// export const endpoints = {
//   baseUrl: "https://krt-backend-json-server-production-5cc1.up.railway.app",
//   employees: "/users",
//   menu: "/menu",
//   points: "/points",
//   branches: "/branches",
//   roles: "/roles",
//   branchList: "/branchList",
//   roleList: "/roleList",
//   pointsEarnedByDriver: "/pointsEarnedByDriver",
//   pointReqHistory: "/pointReqHistory",
//   pointsRequested: "/pointsRequested",
//   createEmp: "/createEmp",
//   createBranch: "/createBranch",
//   createRole: "/createRole",
//   givePoint: "/givePoint",
//   userOptions: "/userOptions",
//   creditPoint: "/creditPoint",
//   pointRequestFromBM: "/pointRequestFromBM",
//   login: "/auth/login",
//   logout: "/logout",
// };
