// export const endpoints = {
//   baseUrl: "http://localhost:4000",
//   employees: "/users",
//   menu: "/menu",
//   points: "/points",
//   branches: "/branches",
//   roles: "/roles",
//   branchList: "/branchList",
//   roleList: "/roleList",
//   pointsEarnedByDriver: "/pointsEarnedByDriver",
//   pointReqHistory: "/pointReqHistory",
//   pointsRequested: "/pointsRequested",
//   createEmp: "/createEmp",
//   createBranch: "/createBranch",
//   createRole: "/createRole",
//   givePoint: "/givePoint",
//   userOptions: "/userOptions",
//   login: "/login",
//   logout: "/logout",
// };

export const endpoints = {
  baseUrl: "https://krt-backend-json-server-production-5cc1.up.railway.app",
  employees: "/user/getAllUsers",
  menu: "/getUiMenu",
  points: "/webRequest/driverInfo",
  branches: "/branchList",
  roles: "/roleList",
  roleList: "/roleList",
  pointsEarnedByDriver: "/webRequest/pointAccommodatedData",
  pointReqHistory: "/webRequest/pointWithdrawalData",
  pointsRequested: "/points/withdrawRequest",
  createEmp: "/src/assets/CreateEmployee.json",
  createBranch: "/src/assets/CreateBranch.json",
  createRole: "/src/assets/CreateRole.json",
  givePoint: "/src/assets/GivePoint.json",
  creditPoint: "/src/assets/CreditPoints.json",
  assignCreditPoint: "/points/creditPoints",
  userOptions: "/userOptions",
  pointRequestFromBM: "/pointRequestFromBM",
  login: "/auth/webLogin",
  logout: "/logout",
  acceptPointRequest: "/points/responseWithdrawRequest",
  allDrivers: "/allDrivers",
  driversPointDisplay: "/webRequest/driverInfoWithPoint",
  getAllGivePoint: "/points/pendingGivePoint",
  postGivePoint: "/points/givePoints",
  postAcceptGivePoint: "/points/approvePoints",
  branchManagers: "/user/getUserByRole",
  givePointValuesLocal: "/src/assets/givePointsValue.json",
  // Employee POST
  createEmployeePOST: "/user/saveUser",
  updateUserPUT: "/user/updateUser",
  deleteUserDel: "/user/delUser",
  // Branch
  createBranchPOST: "/saveBranch",
  updateBranchPUT: "/updateBranch",
  deleteBranchDel: "/delBranch",
  // Role
  createRolePOST: "/saveRole",
  updateRolePUT: "/updateRole",
  deleteRoleDel: "/delRole",
  // Message
  sendMessage: "/sendMessage", // ! need change
  rolesDropdownForMessage: "/getRolesDropdownForMessage", // ! need change
};
// export const endpoints = {
//   baseUrl: "https://krt-backend-json-server-production-5cc1.up.railway.app",
//   employees: "/users",
//   menu: "/menu",
//   points: "/points",
//   branches: "/branches",
//   roles: "/roles",
//   branchList: "/branchList",
//   roleList: "/roleList",
//   pointsEarnedByDriver: "/pointsEarnedByDriver",
//   pointReqHistory: "/pointReqHistory",
//   pointsRequested: "/pointsRequested",
//   createEmp: "/createEmp",
//   createBranch: "/createBranch",
//   createRole: "/createRole",
//   givePoint: "/givePoint",
//   userOptions: "/userOptions",
//   creditPoint: "/creditPoint",
//   pointRequestFromBM: "/pointRequestFromBM",
//   login: "/auth/login",
//   logout: "/logout",
// };
