// export const endpoints = {
//   baseUrl: "http://localhost:4000",
//   employees: "/users",
//   menu: "/menu",
//   points: "/points",
//   branches: "/branches",
//   roles: "/roles",
//   branchList: "/branchList",
//   roleList: "/roleList",
//   pointsEarnedByDriver: "/pointsEarnedByDriver",
//   pointReqHistory: "/pointReqHistory",
//   pointsRequested: "/pointsRequested",
//   createEmp: "/createEmp",
//   createBranch: "/createBranch",
//   createRole: "/createRole",
//   givePoint: "/givePoint",
//   userOptions: "/userOptions",
//   login: "/login",
//   logout: "/logout",
// };

export const endpoints = {
  baseUrl: "https://krt-backend-json-server-production-5cc1.up.railway.app",
  employees: "/user/getAllUsers",
  menu: "/getUiMenu",
  points: "/webRequest/driverInfo",
  branches: "/branchList",
  roles: "/roleList",
  branchList: "/branchList",
  roleList: "/roleList",
  pointsEarnedByDriver: "/webRequest/pointAccommodatedData",
  pointReqHistory: "/webRequest/pointWithdrawalData",
  pointsRequested: "/points/withdrawRequest",
  createEmp: "/src/assets/CreateEmployee.json",
  createBranch: "/src/assets/CreateBranch.json",
  createRole: "/src/assets/CreateRole.json",
  givePoint: "/src/assets/GivePoint.json",
  creditPoint: "/src/assets/CreditPoints.json",
  userOptions: "/userOptions",
  pointRequestFromBM: "/pointRequestFromBM",
  login: "/auth/login",
  logout: "/logout",
};
// export const endpoints = {
//   baseUrl: "https://krt-backend-json-server-production-5cc1.up.railway.app",
//   employees: "/users",
//   menu: "/menu",
//   points: "/points",
//   branches: "/branches",
//   roles: "/roles",
//   branchList: "/branchList",
//   roleList: "/roleList",
//   pointsEarnedByDriver: "/pointsEarnedByDriver",
//   pointReqHistory: "/pointReqHistory",
//   pointsRequested: "/pointsRequested",
//   createEmp: "/createEmp",
//   createBranch: "/createBranch",
//   createRole: "/createRole",
//   givePoint: "/givePoint",
//   userOptions: "/userOptions",
//   creditPoint: "/creditPoint",
//   pointRequestFromBM: "/pointRequestFromBM",
//   login: "/auth/login",
//   logout: "/logout",
// };
